// ◊·κ=1 · Annex IV documentation generator · pure functions · zero deps · v1.1

export const DOC_FIELDS = [
  { id: 'system_name', q: 'System name & version', placeholder: 'e.g. FallVet CV Scorer v2.3', art: 'Annex IV(1)(a)' },
  { id: 'provider', q: 'Provider name + address + contact', placeholder: 'Your company · registered address · contact email', art: 'Annex IV(1)(a)' },
  { id: 'purpose', q: 'Intended purpose (specific use case)', placeholder: 'Scoring software-engineer CVs against role specifications', art: 'Annex IV(1)(b)' },
  { id: 'users', q: 'Intended users + deployment context', placeholder: 'In-house recruiters at Acme GmbH · German labour market', art: 'Annex IV(1)(c)' },
  { id: 'architecture', q: 'System architecture · models · components', placeholder: 'TF-IDF + logistic regression · BERT embeddings · scoring rubric', art: 'Annex IV(2)(a)' },
  { id: 'training_data', q: 'Training data origin · curation · annotation', placeholder: '5000 anonymised CVs + role pairings · 3 senior recruiters', art: 'Annex IV(2)(d)' },
  { id: 'data_governance', q: 'Data governance · bias examination', placeholder: 'Group-fairness metrics (TPR · FPR) measured per protected attribute', art: 'Article 10' },
  { id: 'risk_mgmt', q: 'Risk management system', placeholder: 'Risk: bias against career gaps → mitigation: feature exclusion + review', art: 'Article 9' },
  { id: 'accuracy', q: 'Accuracy metrics + test datasets + results', placeholder: 'F1 = 0.83 on held-out test (n=500) · ROC-AUC = 0.91', art: 'Article 15' },
  { id: 'human_oversight', q: 'Human oversight measures', placeholder: 'Threshold gate · stop button · audit log of overrides', art: 'Article 14' },
  { id: 'cybersecurity', q: 'Cybersecurity measures', placeholder: 'Input sanitisation · adversarial testing · client-side execution', art: 'Article 15' },
  { id: 'logging', q: 'Logging design', placeholder: 'Inference log + SHA-256 prevHash chain · 12-month IndexedDB retention', art: 'Article 12' },
  { id: 'instructions', q: 'Instructions for deployers', placeholder: 'User guide · limitations · threshold tuning · escalation paths', art: 'Article 13' },
  { id: 'post_market', q: 'Post-market monitoring + serious incident reporting', placeholder: 'Weekly dashboard · 24h triage SLA · authority contact list', art: 'Articles 72-73' },
];

/**
 * Generate an Annex IV technical documentation Markdown file from field values.
 * @param {object} values - keyed by DOC_FIELDS id
 * @param {{ date?: string, draftWarning?: boolean }} opts
 * @returns {string} markdown document
 */
export function generateAnnexIV(values, opts = {}) {
  values = values || {};
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const draftWarning = opts.draftWarning !== false;
  const v = id => values[id] || '_[fill in]_';

  let md = `# Technical Documentation · EU AI Act Annex IV\n\n`;
  md += `> Generated: ${date} · per Regulation (EU) 2024/1689\n\n`;
  if (draftWarning) {
    md += `> ⚠ This is a starting draft. Review with qualified counsel before use as official conformity documentation.\n\n`;
  }
  md += `---\n\n## 1 · General description\n\n`;
  md += `**System name & version:** ${v('system_name')}\n\n`;
  md += `**Provider:** ${v('provider')}\n\n`;
  md += `**Intended purpose:** ${v('purpose')}\n\n`;
  md += `**Intended users + deployment context:** ${v('users')}\n\n`;
  md += `---\n\n## 2 · Description of system elements\n\n`;
  md += `### 2.1 Architecture & components\n\n${v('architecture')}\n\n`;
  md += `### 2.2 Training data (Article 10)\n\n${v('training_data')}\n\n`;
  md += `### 2.3 Data governance & bias examination\n\n${v('data_governance')}\n\n`;
  md += `### 2.4 Risk management system (Article 9)\n\n${v('risk_mgmt')}\n\n`;
  md += `### 2.5 Accuracy, robustness & cybersecurity (Article 15)\n\n**Accuracy:** ${v('accuracy')}\n\n`;
  md += `**Cybersecurity:** ${v('cybersecurity')}\n\n`;
  md += `### 2.6 Human oversight (Article 14)\n\n${v('human_oversight')}\n\n`;
  md += `### 2.7 Logging (Article 12)\n\n${v('logging')}\n\n`;
  md += `---\n\n## 3 · Instructions for deployers (Article 13)\n\n${v('instructions')}\n\n`;
  md += `---\n\n## 4 · Post-market monitoring & incident reporting (Articles 72-73)\n\n${v('post_market')}\n\n`;
  md += `---\n\n## 5 · EU Declaration of Conformity (Article 47)\n\n`;
  md += `_To be signed by the provider once all other sections are complete and verified by qualified counsel._\n\n`;
  md += `- Name & address of provider: _[fill in]_\n`;
  md += `- AI system identification: ${v('system_name')}\n`;
  md += `- Declaration of conformity with Regulation (EU) 2024/1689\n`;
  md += `- Harmonised standards applied: _[list if applicable]_\n`;
  md += `- Date · Place · Signature\n\n`;
  md += `---\n\n_Generated by fall-euaiact SDK · MIT · github.com/sjgant80-hub/fall-euaiact_\n`;
  return md;
}

export function getDocFields() { return DOC_FIELDS.slice(); }

export function validateValues(values) {
  return DOC_FIELDS.filter(f => !values?.[f.id] || !values[f.id].trim()).map(f => f.id);
}

// ═════════════════════════════════════════════════════════════
// v1.1 · createAnnexIV factory · richer object-oriented API
// returned object has .export({format, language}) and .sign(privKeyHex)
// fully backward-compatible with generateAnnexIV (just adds a wrapper layer)
// ═════════════════════════════════════════════════════════════

export const ANNEX_IV_LOCALES = {
  en: { title:'Technical Documentation · EU AI Act Annex IV', sect1:'General description', sect2:'Description of system elements', sect3:'Instructions for deployers', sect4:'Post-market monitoring & incident reporting', sect5:'EU Declaration of Conformity', draftWarn:'⚠ This is a starting draft. Review with qualified counsel before use as official conformity documentation.' },
  de: { title:'Technische Dokumentation · EU KI-Verordnung Anhang IV', sect1:'Allgemeine Beschreibung', sect2:'Beschreibung der Systemelemente', sect3:'Anweisungen für Anbieter', sect4:'Marktüberwachung und Vorfallmeldung', sect5:'EU-Konformitätserklärung', draftWarn:'⚠ Dies ist ein Entwurf. Vor Verwendung als offizielle Konformitätsdokumentation von qualifiziertem Rechtsbeistand prüfen lassen.' },
  fr: { title:'Documentation technique · Annexe IV du Règlement IA de l\'UE', sect1:'Description générale', sect2:'Description des éléments du système', sect3:'Instructions pour les déployeurs', sect4:'Surveillance post-commercialisation et signalement d\'incidents', sect5:'Déclaration UE de conformité', draftWarn:'⚠ Ceci est une ébauche. À vérifier avec un conseil juridique qualifié avant utilisation comme documentation officielle de conformité.' },
  es: { title:'Documentación técnica · Anexo IV del Reglamento de IA de la UE', sect1:'Descripción general', sect2:'Descripción de elementos del sistema', sect3:'Instrucciones para implementadores', sect4:'Vigilancia post-comercialización e informe de incidentes', sect5:'Declaración UE de conformidad', draftWarn:'⚠ Este es un borrador. Revisar con asesoría legal cualificada antes de usar como documentación oficial de conformidad.' },
  it: { title:'Documentazione tecnica · Allegato IV del Regolamento UE sull\'IA', sect1:'Descrizione generale', sect2:'Descrizione degli elementi del sistema', sect3:'Istruzioni per i distributori', sect4:'Sorveglianza post-commercializzazione e segnalazione di incidenti', sect5:'Dichiarazione UE di conformità', draftWarn:'⚠ Questa è una bozza. Da verificare con consulenza legale qualificata prima di usare come documentazione ufficiale di conformità.' },
  nl: { title:'Technische documentatie · EU AI-Verordening Bijlage IV', sect1:'Algemene beschrijving', sect2:'Beschrijving van systeemelementen', sect3:'Instructies voor implementatoren', sect4:'Markttoezicht en incidentmelding', sect5:'EU-conformiteitsverklaring', draftWarn:'⚠ Dit is een conceptversie. Laat dit nakijken door gekwalificeerd juridisch advies voordat u dit als officiële conformiteitsdocumentatie gebruikt.' },
};

const SUPPORTED_LANGS = Object.keys(ANNEX_IV_LOCALES);
const SUPPORTED_FORMATS = ['markdown', 'html', 'json'];

function mdToHtml(md, titleText) {
  const safe = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const html = safe(md)
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^&gt; ⚠ (.+)$/gm, '<blockquote class="warn">⚠ $1</blockquote>')
    .replace(/^&gt; (.+)$/gm, '<blockquote>$1</blockquote>')
    .replace(/^---$/gm, '<hr/>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/_\[fill in\]_/g, '<em class="todo">[fill in]</em>')
    .replace(/_(.+?)_/g, '<em>$1</em>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, m => '<ul>' + m + '</ul>')
    .split(/\n\n+/).map(p => p.trim().startsWith('<') ? p : (p ? '<p>' + p + '</p>' : '')).join('\n');
  return `<!doctype html>
<html><head><meta charset="utf-8"><title>${safe(titleText)}</title>
<style>
:root{--ink:#1a1a22;--accent:#8b1a1a;--soft:#5a5a62}
body{font:14px/1.65 -apple-system,system-ui,"Segoe UI",serif;color:var(--ink);background:#fff;max-width:780px;margin:32px auto;padding:0 20px}
h1{font:700 26px/1.1 'Times New Roman',serif;border-bottom:2px solid var(--accent);padding-bottom:8px;margin-top:32px}
h2{font:600 18px/1.2 'Times New Roman',serif;color:var(--accent);margin-top:28px}
h3{font:600 15px/1.2 'Times New Roman',serif;margin-top:18px}
hr{border:0;border-top:1px solid #ddd;margin:18px 0}
blockquote{border-left:3px solid var(--accent);padding:6px 14px;color:var(--soft);font-style:italic}
blockquote.warn{border-color:#c4990a;background:#fffbe6;color:#5a3d00}
em.todo{color:#999}
ul{margin:6px 0;padding-left:22px}
@media print{body{margin:0;max-width:none;padding:24mm 18mm}}
</style></head><body>
${html}
</body></html>`;
}

function buildEnvelope(values, language, opts) {
  return {
    kind: 'fall-euaiact-annexiv-v1',
    spec: 'Regulation (EU) 2024/1689',
    language,
    generated: opts.date || new Date().toISOString().slice(0, 10),
    systemName: values.system_name || null,
    provider: values.provider || null,
    purpose: values.purpose || null,
    intendedUsers: values.users || null,
    architecture: values.architecture || null,
    trainingData: values.training_data || null,
    dataGovernance: values.data_governance || null,
    riskManagement: values.risk_mgmt || null,
    accuracy: values.accuracy || null,
    humanOversight: values.human_oversight || null,
    cybersecurity: values.cybersecurity || null,
    logging: values.logging || null,
    deployerInstructions: values.instructions || null,
    postMarketMonitoring: values.post_market || null,
    fields: DOC_FIELDS.map(f => ({ id: f.id, value: values[f.id] || null, articleRef: f.art })),
  };
}

/**
 * Factory: build an Annex IV documentation object with .export() + .sign().
 * Backward-compatible · generateAnnexIV() still works for markdown-only use.
 *
 * @example
 *   import { createAnnexIV } from '@sjgant80-hub/fall-euaiact';
 *   const doc = createAnnexIV({
 *     system_name: 'My AI v2',
 *     provider: 'Acme Ltd',
 *     purpose: 'Customer support automation',
 *   });
 *   const md   = await doc.export({ format: 'markdown', language: 'en' });
 *   const html = await doc.export({ format: 'html', language: 'de' });
 *   const env  = await doc.export({ format: 'json' });
 *   const { signature } = await doc.sign(yourEd25519PrivKeyHex);
 *
 * @param {object} spec - field values keyed by DOC_FIELDS id
 * @param {{ date?: string, draftWarning?: boolean }} [opts]
 * @returns {object} { export, sign, validate, missing, fields, toJSON, supportedLanguages }
 */
export function createAnnexIV(spec, opts = {}) {
  const values = spec || {};
  const settings = { date: opts.date, draftWarning: opts.draftWarning !== false };

  return {
    fields: DOC_FIELDS.slice(),
    toJSON() { return { values, opts: settings }; },
    missing() { return validateValues(values); },
    validate() { return { complete: this.missing().length === 0, missing: this.missing() }; },
    supportedLanguages: SUPPORTED_LANGS,

    async export(exportOpts = {}) {
      const format = exportOpts.format || 'markdown';
      const lang = exportOpts.language || 'en';
      if (!SUPPORTED_FORMATS.includes(format)) throw new Error('format must be one of: ' + SUPPORTED_FORMATS.join(', '));
      if (!SUPPORTED_LANGS.includes(lang)) throw new Error('language must be one of: ' + SUPPORTED_LANGS.join(', ') + ' (community translations welcome via PR to ANNEX_IV_LOCALES)');
      const locale = ANNEX_IV_LOCALES[lang];
      let md = generateAnnexIV(values, settings);
      if (lang !== 'en') {
        md = md.replace('Technical Documentation · EU AI Act Annex IV', locale.title);
        md = md.replace(/⚠ This is a starting draft\. Review with qualified counsel before use as official conformity documentation\./, locale.draftWarn);
        md = md.replace('## 1 · General description', '## 1 · ' + locale.sect1);
        md = md.replace('## 2 · Description of system elements', '## 2 · ' + locale.sect2);
        md = md.replace('## 3 · Instructions for deployers (Article 13)', '## 3 · ' + locale.sect3 + ' (Article 13)');
        md = md.replace('## 4 · Post-market monitoring & incident reporting (Articles 72-73)', '## 4 · ' + locale.sect4 + ' (Articles 72-73)');
        md = md.replace('## 5 · EU Declaration of Conformity (Article 47)', '## 5 · ' + locale.sect5 + ' (Article 47)');
      }
      if (format === 'markdown') return md;
      if (format === 'html') return mdToHtml(md, locale.title);
      if (format === 'json') return buildEnvelope(values, lang, settings);
    },

    async sign(privateKeyHex) {
      const { sign } = await import('./sign.js');
      const env = buildEnvelope(values, 'en', settings);
      const signature = await sign(JSON.stringify(env), privateKeyHex);
      return { envelope: env, signature };
    },
  };
}
