// ◊·κ=1 · fall-euaiact · Article 50 transparency disclosure component · v1.1
// MIT · zero hard deps · libsodium lazy-loaded only when sign() is called

/**
 * Article 50 of the EU AI Act requires AI systems that interact with humans
 * to disclose their AI nature. Five categories are covered by this SDK:
 *
 *   · chatbot          · the system converses with the user
 *   · generated-text   · text content not authored by a human
 *   · generated-image  · synthetic or substantially modified images
 *   · audio            · synthetic voice or substantially modified audio
 *   · video            · synthetic or deepfake video
 *
 * The compliance bar is in Article 50(1): "in a clear and distinguishable
 * manner at the latest at the time of the first interaction or exposure."
 * That's it. The Act does NOT specify what a badge looks like · it specifies
 * what it must ACHIEVE. So we ship a sensible default that meets the bar
 * and let the consumer style it.
 */
export const ARTICLE_50_CATEGORIES = ['chatbot', 'generated-text', 'generated-image', 'audio', 'video'];

const DEFAULT_LABELS = {
  en: {
    chatbot:           'You are interacting with an AI · not a human.',
    'generated-text':  'This text was generated by AI.',
    'generated-image': 'This image was generated or substantially modified by AI.',
    audio:             'This audio was generated by AI.',
    video:             'This video contains AI-generated or substantially modified content.',
    optOut:            'Prefer a human?',
  },
  de: {
    chatbot:           'Sie interagieren mit einer KI · nicht mit einem Menschen.',
    'generated-text':  'Dieser Text wurde von KI erstellt.',
    'generated-image': 'Dieses Bild wurde durch KI erstellt oder wesentlich verändert.',
    audio:             'Dieses Audio wurde von KI erstellt.',
    video:             'Dieses Video enthält durch KI erstellte oder wesentlich veränderte Inhalte.',
    optOut:            'Lieber einen Menschen?',
  },
  fr: {
    chatbot:           'Vous interagissez avec une IA · pas un humain.',
    'generated-text':  'Ce texte a été généré par une IA.',
    'generated-image': 'Cette image a été générée ou substantiellement modifiée par une IA.',
    audio:             'Cet audio a été généré par une IA.',
    video:             'Cette vidéo contient du contenu généré ou substantiellement modifié par une IA.',
    optOut:            'Préférez un humain ?',
  },
  es: {
    chatbot:           'Está interactuando con una IA · no con un humano.',
    'generated-text':  'Este texto fue generado por IA.',
    'generated-image': 'Esta imagen fue generada o modificada sustancialmente por IA.',
    audio:             'Este audio fue generado por IA.',
    video:             'Este vídeo contiene contenido generado o modificado sustancialmente por IA.',
    optOut:            '¿Prefiere un humano?',
  },
  it: {
    chatbot:           'Stai interagendo con un\'IA · non un umano.',
    'generated-text':  'Questo testo è stato generato da IA.',
    'generated-image': 'Questa immagine è stata generata o sostanzialmente modificata da IA.',
    audio:             'Questo audio è stato generato da IA.',
    video:             'Questo video contiene contenuti generati o sostanzialmente modificati da IA.',
    optOut:            'Preferisci un umano?',
  },
  nl: {
    chatbot:           'U communiceert met een AI · geen mens.',
    'generated-text':  'Deze tekst is gegenereerd door AI.',
    'generated-image': 'Deze afbeelding is gegenereerd of substantieel gewijzigd door AI.',
    audio:             'Deze audio is gegenereerd door AI.',
    video:             'Deze video bevat AI-gegenereerde of substantieel gewijzigde inhoud.',
    optOut:            'Liever een mens?',
  },
};

const SUPPORTED_LANGS = Object.keys(DEFAULT_LABELS);

function esc(s) { return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

/**
 * Factory: build an Article 50 transparency badge with HTML rendering,
 * DOM mounting, impression-logging, and audit-export.
 *
 * @example
 *   import { createTransparencyBadge } from '@sjgant80-hub/fall-euaiact';
 *   const badge = createTransparencyBadge({
 *     category: 'chatbot',
 *     language: 'en',
 *     systemId: 'support-bot-v3',
 *     optOutUrl: '/preferences/turn-off-ai'
 *   });
 *   // in the browser
 *   badge.mount('#chat-header');
 *   // log impressions (Article 50 has no explicit logging duty but Article 26 does)
 *   await badge.recordImpression('user-12345');
 *   // export the log for the regulator
 *   const log = await badge.export({ from: '2026-01-01' });
 *
 * @param {object} spec
 * @param {string} spec.category - one of ARTICLE_50_CATEGORIES
 * @param {string} [spec.language='en'] - BCP-47 language code (en/de/fr/es/it/nl)
 * @param {string} [spec.systemId] - your AI system identifier (recorded with impressions)
 * @param {string} [spec.optOutUrl] - where the user can request a human (if applicable)
 * @param {string} [spec.customLabel] - override the default disclosure label
 * @param {object} [spec.styleVars] - { bg, fg, accent } CSS color overrides
 * @returns {object} { html, mount, recordImpression, export, sign, toJSON, supportedLanguages }
 */
export function createTransparencyBadge(spec) {
  spec = spec || {};
  if (!spec.category || !ARTICLE_50_CATEGORIES.includes(spec.category)) {
    throw new Error('category must be one of: ' + ARTICLE_50_CATEGORIES.join(', '));
  }
  const lang = spec.language || 'en';
  if (!SUPPORTED_LANGS.includes(lang)) {
    throw new Error('language must be one of: ' + SUPPORTED_LANGS.join(', ') + ' (PR more locales to DEFAULT_LABELS)');
  }
  const labels = DEFAULT_LABELS[lang];
  const label = spec.customLabel || labels[spec.category];
  const systemId = spec.systemId || 'unknown';
  const optOutUrl = spec.optOutUrl || null;
  const style = Object.assign({ bg: '#11131a', fg: '#e8e8ea', accent: '#b8974a' }, spec.styleVars || {});

  // ─ in-memory impression log · v1 simple · v2 will integrate IndexedDB
  const impressions = [];

  return {
    /** SUPPORTED LANGUAGE LIST · for diagnostics */
    supportedLanguages: SUPPORTED_LANGS,

    /** Round-trip the spec for storage */
    toJSON() { return { category: spec.category, language: lang, systemId, optOutUrl, label }; },

    /**
     * Render the disclosure as an HTML string.
     * Accessible · role=note · screen-reader-friendly · A11y-compliant.
     *
     * @param {{ compact?: boolean }} [opts]
     * @returns {string} HTML string
     */
    html(opts = {}) {
      const compact = !!opts.compact;
      const optOutHtml = optOutUrl ? ` <a href="${esc(optOutUrl)}" style="color:${style.accent};text-decoration:underline">${esc(labels.optOut)}</a>` : '';
      return `<div class="ai-disclosure" role="note" aria-label="AI disclosure · Article 50 EU AI Act" data-system-id="${esc(systemId)}" data-category="${esc(spec.category)}" data-language="${esc(lang)}" style="
display:inline-flex;align-items:center;gap:8px;
background:${esc(style.bg)};color:${esc(style.fg)};
font:${compact ? '11px' : '12.5px'}/1.4 -apple-system,system-ui,sans-serif;
padding:${compact ? '3px 9px' : '6px 12px'};border-radius:14px;
border:1px solid ${esc(style.accent)};letter-spacing:.2px">
<span aria-hidden="true" style="color:${esc(style.accent)};font-weight:700">◊</span>
<span>${esc(label)}${optOutHtml}</span>
</div>`;
    },

    /**
     * Mount the disclosure into a DOM element (browser only).
     * @param {string|Element} selectorOrEl
     * @param {object} [opts] - passed through to html()
     */
    mount(selectorOrEl, opts = {}) {
      if (typeof document === 'undefined') throw new Error('mount() requires a browser environment');
      const el = typeof selectorOrEl === 'string' ? document.querySelector(selectorOrEl) : selectorOrEl;
      if (!el) throw new Error('mount target not found: ' + selectorOrEl);
      const wrapper = document.createElement('div');
      wrapper.innerHTML = this.html(opts);
      el.appendChild(wrapper.firstChild);
      return el;
    },

    /**
     * Record that the disclosure was shown to a user. Article 50 doesn't
     * explicitly require this · but Article 26 (deployer record-keeping)
     * benefits from it, and your post-market monitoring (Articles 72-73)
     * will eventually need impression counts.
     *
     * @param {string} userId
     * @param {object} [meta]
     * @returns {Promise<{ ts: number, userId: string, systemId: string, category: string, language: string }>}
     */
    async recordImpression(userId, meta = {}) {
      const entry = { ts: Date.now(), userId: String(userId || 'anonymous'), systemId, category: spec.category, language: lang, ...meta };
      impressions.push(entry);
      return entry;
    },

    /**
     * Export the impression log for a date range.
     * @param {{ from?: string, to?: string }} [range] ISO dates
     * @returns {Promise<Array<object>>}
     */
    async export(range = {}) {
      const fromTs = range.from ? Date.parse(range.from) : 0;
      const toTs = range.to ? Date.parse(range.to) : Date.now();
      return impressions.filter(e => e.ts >= fromTs && e.ts <= toTs);
    },

    /**
     * Sign the badge configuration · proves you ARE running disclosure for
     * this specific system at this specific time. Useful evidence layer
     * for the post-market monitoring portfolio.
     *
     * @param {string} privateKeyHex
     * @returns {Promise<{ envelope: object, signature: string }>}
     */
    async sign(privateKeyHex) {
      const { sign } = await import('./sign.js');
      const envelope = {
        kind: 'fall-euaiact-article50-badge-v1',
        category: spec.category,
        language: lang,
        systemId,
        labelHash: await hashLabel(label),
        recordedAt: new Date().toISOString(),
        impressionsCount: impressions.length,
      };
      const signature = await sign(JSON.stringify(envelope), privateKeyHex);
      return { envelope, signature };
    },
  };
}

async function hashLabel(text) {
  if (typeof crypto !== 'undefined' && crypto.subtle) {
    const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(text));
    return [...new Uint8Array(buf)].map(b => b.toString(16).padStart(2, '0')).join('');
  }
  // Node fallback
  const { createHash } = await import('node:crypto');
  return createHash('sha256').update(text).digest('hex');
}
